### ISSUE TITLE
BUG npm run format does not run

### ISSUE THREAD

**Issue by tommyconner96** [Lambda-School-Labs/xcel-wom-be-c#38]
`npm run format `

gives the following error:
`> npx prettier --write "**/*.+(js|jsx|json|yml|yaml|css|md)"

'jsx' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by tommyconner96** [comment]
I believe all we need for the prettier line in package.json is:
`    "format": "npx prettier --write ./",`

I made a PR making this change. Thoughts?
https://github.com/Lambda-School-Labs/xcel-wom-be-c/pull/37

**Comment by sophiasagan** [comment]
This change would be helpful as the error does not occur with the suggested changes.
